#!/bin/bash


user=$(whoami)
echo -e "--------------------------------------------------------------------------------------------------------\n"
echo -e "                                        Report Generated by $user                                       \n"
echo -e "--------------------------------------------------------------------------------------------------------\n"


#Todays date
today=$(date | awk '{print $3"/"$2"/"$6}')

echo -e "Today's date: $today\n"

#Server Uptime
echo -e "Server Uptime: $(uptime)\n"

echo -e "--------------------------------------------------------------------------------------------------------\n"

#CPU Utilization details
echo -e "############################-- Percentage of CPU Utilization --###########################\n"
cpuutilization=$(mpstat 1 1 | awk '$1 == "Average:" && $2 == "all" {print (100 - $12)"%"}')
echo -e "CPU Utilization : $cpuutilization\n"

echo -e "--------------------------------------------------------------------------------------------------------\n"

#Memory Utiliztion details

echo -e "#########################-- Server Memory Utilization Details --#########################\n"

memoryf=$(free -h | awk 'NR == 2 {print $4}')
echo -e "Free Memory is: $memoryf\n"

memoryt=$(free -h | awk 'NR == 2 {print $2}')
echo -e "Total Memory is $memoryt\n"

memoryut=$(free | awk 'NR == 2 {printf "%.2f%\n", ($3/$2)*100}')
echo -e "Memory Utilization : $memoryut\n"

swaput=$(free | awk 'NR == 3 { if ($2 != 0) { {printf "%.2f%\n", ($3/$2)*100} } else { print "swap total is zero" }}')
echo -e "Swap Utilization : $swaput\n"

echo -e "--------------------------------------------------------------------------------------------------------\n"

#Disk Usage: this option can be used when all mounted filesystems are on the same disk

echo -e "###################################-- Disk Usage --#####################################\n"

diskusge=$(df -h --total | awk '$1 == "total" { print $5}')
echo -e "Disk Usage: $diskusge\n"

#Get disk usage on a secific mount

diskusage=$(df -h / | awk 'NR == 2 {print $5}')
echo -e "Disk Usage on / : $diskusage\n"

echo -e "--------------------------------------------------------------------------------------------------------\n"
echo -e "                                        Thank You!                                                      \n"
echo -e "--------------------------------------------------------------------------------------------------------\n"
